# El nombre que aparecerá en la pestaña 'Actions' de GitHub
name: Integracion Continua - Dia 4

# EVENTO: Qué dispara este pipeline. 
# En este caso: cada vez que se haga un 'push' o un 'pull request' hacia la rama main.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# TRABAJOS: Qué va a hacer la automatización
jobs:
  verificar-script:
    # ENTORNO: La máquina virtual que nos prestará GitHub en la nube
    runs-on: ubuntu-latest

    # PASOS: Las instrucciones secuenciales que ejecutará la máquina
    steps:
      # Paso 1: Usar una acción oficial de GitHub para clonar/descargar nuestro código dentro de la máquina virtual
      - name: Descargar el codigo del repositorio
        uses: actions/checkout@v4

      # Paso 2: Instalar shellcheck en el Ubuntu de la nube para analizar el script
      - name: Instalar validador de Bash (ShellCheck)
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      # Paso 3: Correr el análisis sobre nuestro archivo
      - name: Analizar la sintaxis de script.sh
        run: shellcheck script.sh

      # Paso 4: Darle permisos de ejecución al script y correrlo para ver que funcione
      - name: Ejecutar script de prueba
        run: |
          chmod +x script.sh
          ./script.sh
